#MakeFile for Siexgran's Project
#output file's name'
APP := game
#Compilers variable
CC := g++
C := gcc
#C++ standard variable
CCSTD := -std=c++20 
#C++ flags variable
CCFLAGS := $(CCSTD) -Wall -Wpedantic -Wconversion -fsanitize=undefined 

#LIBS PATHS
#siexgran engine path
ECSENGINE_LIBS_PATH := -Idir "./siexgran engine/"
#opengl render engine path
OPGL_LIBS_PATH := -Idir "./OpenGl/OpenGL3D/include/" -Idir "./OpenGL/OpenGL3D/source/"
'

#SHELL SCRIPTING
#some scripts useful

#Mkdir script
MKDIR := mkdir -p
#src and obj variables
SRC := src
OBJ := obj
#path for every cpp file
ALLCPPS := $(shell find . -iname *.cpp)
ALLCS := $(shell find . -iname *.c)
ALLCPPOBJS := $(OBJ)/$(patsubst %.c,%.o, $(ALLCPPS)%)
ALLCOBJS := $(OBJ)/$(patsubst %.c, %.o, $(ALLCS))


#find all subdirs at project directory
SUBDIRS := $(shell find . -not -path "*.[a-z]*"  -not -path "*include*"-type d)
#all objects from compilation are saved at this path(copy the project folder structure)
OBJSUBDIRS := $(OBJ) / $(SUBDIRS)


.PHONY: dir

$(APP): $(OBJSUBDIRS)

%.o: %.c

$(OBJSUBDIRS): 
	$(MKDIR) $(OBJSUBDIRS)





#dir's rule show us information to creating the makefile
dir:
	$(info $(SUBDIRS))
	$(info $(OBJSUBDIRS))


